[package]
name = "maidata"
version = "0.0.0"
authors = ["WANG Xuerui <git@xen0n.name>"]
edition = "2021"

[dependencies]
nom = "7"
nom_locate = "4"
walkdir = "2"
lazy_static = "1.4.0"
enum-map = "2.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
